spring:
  application:
    name: SupportChatApplication
  zipkin:
    base-url: http://your-zipkin-server-address:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/anirudh?sessionTimezone=Asia/Kolkata
    username: anirudh
    password: anirudh
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092 # Or ms_kafka:9092 if running all in Docker
    consumer:
      group-id: support-chat-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  session:
    store-type: redis
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
kafka: # Add a top-level property for the topic name
  topic:
    incoming-requests: incoming-customer-requests