spring:
  application:
    name: SupportChatApplication
  zipkin:
    base-url: http://your-zipkin-server-address:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/anirudh?sessionTimezone=Asia/Kolkata
    username: anirudh
    password: anirudh
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  session:
    store-type: redis
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8050